/**
 * Static security tests for EU AI Act compliance.
 * Art.50: AI transparency labels on all AI-generated content.
 * Art.53: Model documentation (model cards).
 */
import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';

const ROOT = resolve(__dirname, '../..');
const read = (p: string) =>
  existsSync(resolve(ROOT, p)) ? readFileSync(resolve(ROOT, p), 'utf-8') : '';

describe('EU AI Act Art.50: AI Transparency', () => {
  it('ai-transparency.ts exists', () => {
    expect(
      existsSync(resolve(ROOT, 'apps/subgraph-agent/src/ai/ai-transparency.ts'))
    ).toBe(true);
  });

  it('AITransparencyMetadata interface has isAIGenerated field', () => {
    const c = read('apps/subgraph-agent/src/ai/ai-transparency.ts');
    expect(c).toContain('isAIGenerated');
  });

  it('AITransparencyMetadata includes modelUsed field', () => {
    const c = read('apps/subgraph-agent/src/ai/ai-transparency.ts');
    expect(c).toContain('modelUsed');
  });

  it('AITransparencyMetadata includes humanReviewRequired field', () => {
    const c = read('apps/subgraph-agent/src/ai/ai-transparency.ts');
    expect(c).toContain('humanReviewRequired');
  });

  it('formatTransparencyLabel returns string describing AI origin', () => {
    const c = read('apps/subgraph-agent/src/ai/ai-transparency.ts');
    expect(c).toContain('formatTransparencyLabel');
    expect(c).toContain('Generated by');
  });

  it('requiresHumanReview returns true for grade-impacting assessments', () => {
    const c = read('apps/subgraph-agent/src/ai/ai-transparency.ts');
    expect(c).toContain('requiresHumanReview');
    expect(c).toContain('impactsGrade');
  });
});

describe('EU AI Act: AI Opt-Out Preferences', () => {
  it('AIOptOutPreferences interface exists', () => {
    const c = read('apps/subgraph-agent/src/ai/ai-transparency.ts');
    expect(c).toContain('AIOptOutPreferences');
  });

  it('externalLLMEnabled defaults to false (opt-in model)', () => {
    const c = read('apps/subgraph-agent/src/ai/ai-transparency.ts');
    expect(c).toContain('externalLLMEnabled: false');
  });

  it('per-agent-type opt-out supported', () => {
    const c = read('apps/subgraph-agent/src/ai/ai-transparency.ts');
    expect(c).toContain('agentTypes');
    expect(c).toContain('CHAVRUTA');
    expect(c).toContain('QUIZ_MASTER');
  });
});

describe('EU AI Act Art.53: Model Documentation', () => {
  it('MODEL_CARDS.md exists', () => {
    expect(existsSync(resolve(ROOT, 'docs/ai/MODEL_CARDS.md'))).toBe(true);
  });

  it('MODEL_CARDS.md documents all agent types', () => {
    const c = read('docs/ai/MODEL_CARDS.md');
    expect(c).toContain('CHAVRUTA');
    expect(c).toContain('QUIZ_MASTER');
    expect(c).toContain('SUMMARIZER');
    expect(c).toContain('DEBATE');
  });

  it('MODEL_CARDS.md identifies high-risk agents', () => {
    const c = read('docs/ai/MODEL_CARDS.md');
    expect(c).toMatch(/HIGH-RISK|high.risk/i);
  });

  it('MODEL_CARDS.md documents human oversight requirements', () => {
    const c = read('docs/ai/MODEL_CARDS.md');
    expect(c).toMatch(/human oversight|REQUIRED/i);
  });

  it('MODEL_CARDS.md documents data retention', () => {
    const c = read('docs/ai/MODEL_CARDS.md');
    expect(c).toMatch(/retention|days/i);
  });

  it('MODEL_CARDS.md documents opt-out mechanism', () => {
    const c = read('docs/ai/MODEL_CARDS.md');
    expect(c).toContain('opt');
  });

  it('MODEL_CARDS.md confirms PII not sent to external LLM', () => {
    const c = read('docs/ai/MODEL_CARDS.md');
    expect(c).toMatch(/PII.*scrub|scrub.*PII|No.*scrubbed/i);
  });
});
