export const PUBLIC_ROUTES = [
  '/',
  '/login',
  '/landing',
  '/demo',
  '/contact',
  '/compliance',
  '/features/:featureSlug',
  '/features',
  '/solutions/:solutionSlug',
  '/solutions',
  '/privacy',
  '/terms',
  '/about',
  '/careers',
  '/accessibility',
  '/faq',
  '/glossary',
  '/pricing',
  '/catalog',
  '/instructors',
  '/blog',
  '/blog/:slug',
  '/verify/badge/:assertionId',
  '/u/:userId',
  '/portal',
  '/pilot',
  '/partners',
  '/lti/launch',
  '/oauth/google/callback',
];

export const PUBLIC_ROUTES_CONCRETE = [
  '/',
  '/login',
  '/landing',
  '/contact',
  '/compliance',
  '/features',
  '/solutions',
  '/privacy',
  '/terms',
  '/about',
  '/careers',
  '/accessibility',
  '/faq',
  '/glossary',
  '/pricing',
  '/catalog',
  '/instructors',
  '/blog',
  '/portal',
  '/pilot',
  '/partners',
];

export const PROTECTED_ROUTES_CONCRETE = [
  '/dashboard',
  '/dashboard/legacy',
  '/courses',
  '/courses/new',
  '/explore',
  '/discover',
  '/courses/discover',
  '/graph',
  '/knowledge-graph',
  '/agents',
  '/agents/studio',
  '/annotations',
  '/annotations-demo',
  '/collaboration',
  '/collaboration/session',
  '/search',
  '/profile',
  '/settings',
  '/settings/theme',
  '/chavruta',
  '/scenarios',
  '/programs',
  '/marketplace',
  '/checkout',
  '/instructor/analytics',
  '/instructor/merge-queue',
  '/instructor/earnings',
  '/library',
  '/library/compliance',
  '/srs-review',
  '/notifications',
  '/leaderboard',
  '/gamification',
  '/my-badges',
  '/my-progress',
  '/skills',
  '/social',
  '/social-feed',
  '/people',
  '/discussions',
  '/peer-review',
  '/assessments',
  '/challenges',
  '/peer-matching',
  '/chavruta/partner',
  '/cohort-insights',
  '/partner/dashboard',
  '/manager',
  '/onboarding',
  '/quiz-builder',
  '/certificates',
  '/sessions',
  '/skill-tree',
  '/admin',
  '/admin/branding',
  '/admin/languages',
  '/admin/users',
  '/admin/roles',
  '/admin/gamification',
  '/admin/announcements',
  '/admin/enrollment',
  '/admin/at-risk',
  '/admin/security',
  '/admin/audit',
  '/admin/audit-log',
  '/admin/notifications',
  '/admin/bi-export',
  '/admin/cpd',
  '/admin/analytics',
  '/admin/usage',
  '/admin/platform-usage',
  '/admin/roi-analytics',
  '/admin/lti',
  '/admin/compliance',
  '/admin/scim',
  '/admin/xapi',
  '/admin/assessments',
  '/admin/crm',
  '/admin/language',
  '/admin/portal',
  '/admin/pilot-requests',
  '/admin/hris-config',
  '/admin/auto-grading',
  '/admin/gap-analysis',
  '/admin/invoices',
  '/internal/investor-deck',
];

export const LANDING_NAV_LINKS = [
  { text: 'Features', href: '#features' },
  { text: 'Pricing', href: '#pricing' },
  { text: 'Compliance', href: '/compliance' },
  { text: 'Pilot', href: '#pilot-cta' },
];

export const LANDING_FOOTER_LINKS = [
  // Product column
  { text: 'Features', href: '#features', column: 'Product' },
  { text: 'Pricing', href: '#pricing', column: 'Product' },
  { text: 'AI Course Builder', href: '/features/ai-course-builder', column: 'Product' },
  { text: 'Visual Anchoring', href: '/features/visual-anchoring', column: 'Product' },
  { text: 'Knowledge Graph', href: '/features/knowledge-graph', column: 'Product' },
  // Solutions column
  { text: 'Universities', href: '/solutions/universities', column: 'Solutions' },
  { text: 'Enterprises', href: '/solutions/enterprises', column: 'Solutions' },
  { text: 'Government & Defense', href: '/solutions/government', column: 'Solutions' },
  { text: 'Training Companies', href: '/solutions/training', column: 'Solutions' },
  // Compliance column
  { text: 'FERPA', href: '/compliance#ferpa', column: 'Compliance' },
  { text: 'WCAG 2.2 AA', href: '/compliance#wcag', column: 'Compliance' },
  { text: 'SCORM', href: '/compliance#scorm', column: 'Compliance' },
  { text: 'GDPR', href: '/compliance#gdpr', column: 'Compliance' },
  { text: 'Air-Gapped', href: '/compliance#air-gapped', column: 'Compliance' },
  { text: 'Security', href: '/compliance#security', column: 'Compliance' },
  // Company column
  { text: 'About', href: '/about', column: 'Company' },
  { text: 'Blog', href: '/blog', column: 'Company' },
  { text: 'Careers', href: '/careers', column: 'Company' },
  { text: 'Contact', href: '/contact', column: 'Company' },
  { text: 'Privacy Policy', href: '/privacy', column: 'Company' },
  { text: 'Terms', href: '/terms', column: 'Company' },
  { text: 'Accessibility Statement', href: '/accessibility', column: 'Company' },
];

export const ALL_ANCHOR_LINKS = [
  '#features',
  '#pricing',
  '#pilot-cta',
  '#compliance',
  '#demo',
  '#roi',
  '#testimonials',
  '#ai-course-builder',
];
