/**
 * TopicClusterKMeansService — orchestrator for K-means++ topic clustering.
 *
 * Algorithm steps:
 *  1. Fetch embeddings        → KMeansDataService.fetchEmbeddingRows
 *  2. Filter by course        → KMeansDataService.filterConceptsByCourse
 *  3. Resolve concept names   → KMeansDataService.resolveConceptNames
 *  4. Run k-means++           → runKMeans (kmeans-math.ts)
 *  5. Persist TopicCluster    → CypherTopicClusterService
 *  6. Publish NATS event      → knowledge.topics.clustered
 *
 * Math helpers live in kmeans-math.ts.
 * Data access lives in KMeansDataService.
 */
import { Injectable, Logger, OnModuleDestroy } from '@nestjs/common';
import { connect, StringCodec, type NatsConnection } from 'nats';
import { buildNatsOptions } from '@edusphere/nats-client';
import type { CypherTopicClusterService } from './cypher-topic-cluster.service';
import { KMeansDataService } from './kmeans-data.service';
import { runKMeans } from './kmeans-math';

@Injectable()
export class TopicClusterKMeansService implements OnModuleDestroy {
  private readonly logger = new Logger(TopicClusterKMeansService.name);
  private readonly sc = StringCodec();
  private nc: NatsConnection | null = null;

  constructor(
    private readonly topicClusterService: CypherTopicClusterService,
    private readonly dataService: KMeansDataService
  ) {}

  async onModuleDestroy(): Promise<void> {
    if (this.nc) {
      await this.nc.drain().catch(() => undefined);
      this.nc = null;
    }
  }

  private async getNats(): Promise<NatsConnection> {
    if (!this.nc) this.nc = await connect(buildNatsOptions());
    return this.nc;
  }

  async clusterConceptsByCourse(
    courseId: string,
    k: number,
    tenantId: string
  ): Promise<unknown[]> {
    const embeddingRows = await this.dataService.fetchEmbeddingRows(tenantId);
    if (embeddingRows.length === 0) {
      this.logger.warn(
        `[TopicClusterKMeans] No concept embeddings for tenant ${tenantId}`
      );
      return [];
    }

    const allIds = embeddingRows.map((r) => r.concept_id);
    const courseConceptIds = await this.dataService.filterConceptsByCourse(
      allIds,
      courseId,
      tenantId
    );
    const courseSet = new Set(courseConceptIds);
    const filteredRows = embeddingRows.filter((r) =>
      courseSet.has(r.concept_id)
    );

    if (filteredRows.length === 0) {
      this.logger.warn(
        `[TopicClusterKMeans] No concepts for course ${courseId}, tenant ${tenantId}`
      );
      return [];
    }

    const nameMap = await this.dataService.resolveConceptNames(
      filteredRows.map((r) => r.concept_id),
      tenantId
    );

    const concepts = this.dataService.buildConceptsWithEmbeddings(
      filteredRows,
      nameMap
    );

    if (concepts.length === 0) {
      this.logger.warn(
        `[TopicClusterKMeans] All embeddings were empty for course ${courseId}`
      );
      return [];
    }

    const clusters = runKMeans(concepts, k);

    const created: unknown[] = [];
    for (const cluster of clusters) {
      try {
        const topicCluster = await this.topicClusterService.createTopicCluster(
          cluster.label,
          `Auto-generated by k-means++ (${cluster.conceptIds.length} concepts)`,
          tenantId
        );
        created.push(topicCluster);
      } catch (err) {
        this.logger.error(
          `[TopicClusterKMeans] Failed to persist cluster "${cluster.label}": ${String(err)}`,
          { tenantId, courseId }
        );
      }
    }

    try {
      const nc = await this.getNats();
      nc.publish(
        'knowledge.topics.clustered',
        this.sc.encode(
          JSON.stringify({ courseId, clusterCount: clusters.length, tenantId })
        )
      );
    } catch (err) {
      this.logger.warn(
        `[TopicClusterKMeans] NATS publish failed: ${String(err)}`,
        { tenantId, courseId }
      );
    }

    this.logger.log(
      `[TopicClusterKMeans] Course ${courseId}: ${clusters.length} clusters from ${concepts.length} concepts`,
      { tenantId }
    );
    return created;
  }
}
