import { StyleSheet } from 'react-native';
import { COLORS, SPACING, RADIUS, FONT } from '../../lib/theme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bgCard },
  sectionTitle: {
    fontSize: FONT.xl,
    fontWeight: '600',
    paddingHorizontal: SPACING.lg,
    paddingTop: SPACING.xl,
    paddingBottom: 4,
  },
  sectionTitleSpaced: {
    marginTop: SPACING.md,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: COLORS.border,
  },
  sectionDescription: {
    fontSize: FONT.md,
    color: COLORS.textSecondary,
    paddingHorizontal: SPACING.lg,
    paddingBottom: SPACING.md,
  },
  item: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: SPACING.lg,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.border,
  },
  itemSelected: { backgroundColor: COLORS.primaryLight },
  flag: { fontSize: 24, marginRight: SPACING.md },
  textContainer: { flex: 1 },
  nativeLabel: { fontSize: FONT.base, color: COLORS.textPrimary },
  selectedText: { color: COLORS.primary, fontWeight: '600' },
  englishLabel: { fontSize: FONT.sm, color: COLORS.textSecondary, marginTop: 1 },
  checkmark: { fontSize: 18, color: COLORS.primary, fontWeight: 'bold' },
  syncIndicator: { marginLeft: SPACING.sm },
  loadingRow: { padding: SPACING.xl, alignItems: 'center' },
  storageSection: { paddingHorizontal: SPACING.lg, paddingBottom: 32 },
  warningBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEF2F2',
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    marginBottom: SPACING.md,
  },
  warningBannerYellow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFBEB',
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    marginBottom: SPACING.md,
  },
  warningIcon: { fontSize: 18, marginRight: SPACING.sm },
  warningText: { flex: 1, fontSize: 13, color: COLORS.error },
  warningTextYellow: { flex: 1, fontSize: 13, color: '#92400E' },
  barBackground: {
    height: 8,
    backgroundColor: COLORS.border,
    borderRadius: 4,
    overflow: 'hidden',
    marginBottom: SPACING.sm,
  },
  barFill: { height: '100%', borderRadius: 4 },
  usageLabel: { fontSize: FONT.md, color: COLORS.textPrimary, fontVariant: ['tabular-nums'] },
  usageSubLabel: { fontSize: FONT.sm, color: COLORS.textMuted, marginBottom: SPACING.lg },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.sm,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: RADIUS.md,
    paddingVertical: SPACING.md,
    marginBottom: 10,
  },
  actionButtonDanger: { borderColor: '#FCA5A5' },
  actionButtonText: { fontSize: FONT.md, color: COLORS.textPrimary, fontWeight: '500' },
  actionButtonTextDanger: { color: COLORS.error },
  wifiSection: { paddingBottom: SPACING.sm },
  switchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.border,
  },
  switchLabel: { fontSize: 15, color: COLORS.textPrimary, flex: 1 },
  emptyText: {
    fontSize: FONT.md,
    color: COLORS.textMuted,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
  },
  courseRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: SPACING.md,
    paddingHorizontal: SPACING.lg,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.border,
  },
  courseInfo: { flex: 1, marginRight: SPACING.md },
  courseTitle: { fontSize: 15, color: COLORS.textPrimary, fontWeight: '500' },
  courseMeta: { fontSize: FONT.sm, color: COLORS.textSecondary, marginTop: 2 },
  deleteBtn: {
    borderWidth: 1,
    borderColor: '#FCA5A5',
    borderRadius: RADIUS.sm,
    paddingHorizontal: SPACING.md,
    paddingVertical: 6,
  },
  deleteBtnText: { fontSize: 13, color: COLORS.error, fontWeight: '500' },
});
