import React from 'react';
import { render, screen } from '@testing-library/react';
import { vi, describe, it, expect } from 'vitest';
import { AITransparencyBadge } from './AITransparencyBadge';

// Mock Radix Tooltip (portal issues in jsdom)
vi.mock('@/components/ui/tooltip', () => ({
  TooltipProvider: ({ children }: { children: React.ReactNode }) => (
    <>{children}</>
  ),
  Tooltip: ({ children }: { children: React.ReactNode }) => <>{children}</>,
  TooltipTrigger: ({
    children,
    asChild,
  }: {
    children: React.ReactNode;
    asChild?: boolean;
  }) => {
    void asChild;
    return <>{children}</>;
  },
  TooltipContent: ({
    children,
    id,
  }: {
    children: React.ReactNode;
    id?: string;
  }) => (
    <div id={id} data-testid="tooltip-content">
      {children}
    </div>
  ),
}));

describe('AITransparencyBadge', () => {
  it('renders assessment badge with correct label', () => {
    render(<AITransparencyBadge type="assessment" />);
    const badge = screen.getByTestId('ai-transparency-badge');
    expect(badge.textContent).toContain('AI Assessment');
    expect(badge.textContent).toContain('Subject to human review');
  });

  it('renders recommendation badge', () => {
    render(<AITransparencyBadge type="recommendation" />);
    expect(screen.getByTestId('ai-transparency-badge').textContent).toContain(
      'AI Recommendation'
    );
  });

  it('renders content badge', () => {
    render(<AITransparencyBadge type="content" />);
    expect(screen.getByTestId('ai-transparency-badge').textContent).toContain(
      'AI Generated Content'
    );
  });

  it('renders chat badge', () => {
    render(<AITransparencyBadge type="chat" />);
    expect(screen.getByTestId('ai-transparency-badge').textContent).toContain(
      'AI Assistant'
    );
  });

  it('has role="img" on the badge span', () => {
    render(<AITransparencyBadge type="assessment" />);
    const badge = screen.getByRole('img');
    expect(badge).toBeDefined();
  });

  it('has descriptive aria-label for assessment type', () => {
    render(<AITransparencyBadge type="assessment" />);
    const badge = screen.getByRole('img');
    expect(badge.getAttribute('aria-label')).toContain(
      'AI-generated assessment'
    );
    expect(badge.getAttribute('aria-label')).toContain('human review');
  });

  it('has descriptive aria-label for chat type', () => {
    render(<AITransparencyBadge type="chat" />);
    const badge = screen.getByRole('img');
    expect(badge.getAttribute('aria-label')).toContain('AI assistant');
  });

  it('shows confidence percentage when provided', () => {
    render(<AITransparencyBadge type="assessment" confidence={0.87} />);
    expect(screen.getByTestId('ai-transparency-badge').textContent).toContain(
      '87%'
    );
  });

  it('includes confidence in aria-label when provided', () => {
    render(<AITransparencyBadge type="recommendation" confidence={0.9} />);
    const badge = screen.getByRole('img');
    expect(badge.getAttribute('aria-label')).toContain('90% confidence');
  });

  it('renders tooltip with AI transparency message', () => {
    render(<AITransparencyBadge type="content" />);
    const tooltip = screen.getByTestId('tooltip-content');
    expect(tooltip.textContent).toContain('generated by an AI system');
  });

  it('tooltip contains link to /accessibility page', () => {
    render(<AITransparencyBadge type="content" />);
    const link = screen.getByRole('link', { name: /learn more/i });
    expect(link.getAttribute('href')).toBe('/accessibility');
  });

  it('has aria-describedby pointing to tooltip id', () => {
    render(<AITransparencyBadge type="chat" />);
    const badge = screen.getByTestId('ai-transparency-badge');
    expect(badge.getAttribute('aria-describedby')).toContain('ai-badge-tooltip');
  });

  // Regression guard: EU AI Act compliance reference
  it('EU AI Act Art. 50 reference is present in component source', async () => {
    const src = await import('./AITransparencyBadge?raw');
    expect((src as { default: string }).default).toContain('EU AI Act Art. 50');
  });
});
