// EU AI Act Art. 50 — Transparency for AI-generated content
import React from 'react';
import { cn } from '@/lib/utils';
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/components/ui/tooltip';

export type AIContentType = 'assessment' | 'recommendation' | 'content' | 'chat';

interface AITransparencyBadgeProps {
  type: AIContentType;
  confidence?: number;
  className?: string;
}

const BADGE_CONFIG: Record<
  AIContentType,
  { icon: string; label: string; ariaLabel: string }
> = {
  assessment: {
    icon: '⚖️',
    label: 'AI Assessment — Subject to human review',
    ariaLabel: 'AI-generated assessment, subject to human review',
  },
  recommendation: {
    icon: '🤖',
    label: 'AI Recommendation',
    ariaLabel: 'AI-generated recommendation',
  },
  content: {
    icon: '✨',
    label: 'AI Generated Content',
    ariaLabel: 'AI-generated content',
  },
  chat: {
    icon: '🤖',
    label: 'AI Assistant',
    ariaLabel: 'Response from AI assistant',
  },
};

const TOOLTIP_ID_PREFIX = 'ai-badge-tooltip';

export function AITransparencyBadge({
  type,
  confidence,
  className,
}: AITransparencyBadgeProps) {
  const config = BADGE_CONFIG[type];
  const tooltipId = `${TOOLTIP_ID_PREFIX}-${type}`;
  const confidenceText =
    confidence !== undefined ? ` (${Math.round(confidence * 100)}% confidence)` : '';

  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          <span
            role="img"
            aria-label={`${config.ariaLabel}${confidenceText}`}
            aria-describedby={tooltipId}
            className={cn(
              'inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium',
              'bg-muted text-muted-foreground border border-border',
              'cursor-help select-none',
              className
            )}
            data-testid="ai-transparency-badge"
          >
            <span aria-hidden="true">{config.icon}</span>
            <span>{config.label}</span>
            {confidence !== undefined && (
              <span className="text-muted-foreground/70">
                {Math.round(confidence * 100)}%
              </span>
            )}
          </span>
        </TooltipTrigger>
        <TooltipContent id={tooltipId} className="max-w-xs">
          <p>
            This content was generated by an AI system.{' '}
            <a
              href="/accessibility"
              className="underline hover:no-underline"
              onClick={(e) => e.stopPropagation()}
            >
              Learn more about our AI use.
            </a>
          </p>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
}
