/**
 * EU AI Act — AI Transparency Requirements (effective Aug 2026).
 * All AI-generated content must be labeled and attributable.
 * Reference: EU AI Act Art.50 — Transparency obligations for AI systems.
 */

export interface AITransparencyMetadata {
  /** Always true for AI-generated messages */
  isAIGenerated: boolean;
  /** Model identifier, e.g. "ollama/llama3.2" or "openai/gpt-4o" */
  modelUsed: string;
  /** Whether human instructor review is required before showing to student */
  humanReviewRequired: boolean;
  /** Model confidence if available (0-1) */
  confidenceScore?: number;
}

/** Agent types supported by EduSphere */
export type AgentType =
  | 'CHAVRUTA'
  | 'QUIZ_MASTER'
  | 'SUMMARIZER'
  | 'DEBATE'
  | 'TUTOR';

/**
 * Determine if human review is required based on assessment impact.
 * Per EU AI Act: high-stakes educational assessments need human oversight.
 */
export function requiresHumanReview(params: {
  agentType: AgentType;
  impactsGrade?: boolean;
  isAssessment?: boolean;
}): boolean {
  // High-stakes assessments always need review
  if (params.impactsGrade || params.isAssessment) return true;
  // Quiz results that affect progression need review
  if (params.agentType === 'QUIZ_MASTER' && params.impactsGrade) return true;
  return false;
}

/**
 * Format transparency label for UI display.
 * EU AI Act Art.50: users must know when interacting with AI.
 */
export function formatTransparencyLabel(
  metadata: AITransparencyMetadata
): string {
  const model = metadata.modelUsed.split('/').pop() ?? 'AI';
  return `Generated by ${model} — AI responses may contain errors. Verify important information.`;
}

/** Default AI opt-out preferences structure for user settings */
export interface AIOptOutPreferences {
  /** Master switch — disables all AI features */
  aiAssistantEnabled: boolean;
  /** Allow external LLM calls (OpenAI/Anthropic) */
  externalLLMEnabled: boolean;
  /** Allow behavioral profiling for personalization */
  behaviorProfilingEnabled: boolean;
  /** Per-agent-type opt-out */
  agentTypes: Record<AgentType, boolean>;
}

export const DEFAULT_AI_PREFERENCES: AIOptOutPreferences = {
  aiAssistantEnabled: true,
  externalLLMEnabled: false, // Opt-in by default (requires THIRD_PARTY_LLM consent)
  behaviorProfilingEnabled: false,
  agentTypes: {
    CHAVRUTA: true,
    QUIZ_MASTER: true,
    SUMMARIZER: true,
    DEBATE: true,
    TUTOR: true,
  },
};
