import { describe, it, expect, beforeAll, beforeEach } from 'vitest';
import { BadRequestException } from '@nestjs/common';
import { ImageOptimizerService, ALLOWED_MIME_TYPES } from './image-optimizer.service';

// ── Real image buffers generated by sharp ─────────────────────────────────────
// We use the REAL sharp/file-type (they are installed) so we test actual behavior.
let PNG_BUFFER: Buffer;
let JPEG_BUFFER: Buffer;

const GIF_HEADER = Buffer.from('GIF89a');
const SVG_HEADER = Buffer.from('<svg xmlns="http://www.w3.org/2000/svg"></svg>');
const PDF_BUFFER = Buffer.from('%PDF-1.4');

describe('ImageOptimizerService', () => {
  let service: ImageOptimizerService;

  beforeAll(async () => {
    // Generate 1×1 images via real sharp for integration tests
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const sharp = require('sharp') as (opts: unknown) => {
      png(): { toBuffer(): Promise<Buffer> };
      jpeg(): { toBuffer(): Promise<Buffer> };
    };
    PNG_BUFFER = await sharp({ create: { width: 1, height: 1, channels: 4, background: { r: 255, g: 0, b: 0, alpha: 1 } } })
      .png()
      .toBuffer();
    JPEG_BUFFER = await sharp({ create: { width: 1, height: 1, channels: 3, background: { r: 255, g: 0, b: 0 } } })
      .jpeg({ quality: 80 })
      .toBuffer();
  });

  beforeEach(() => {
    service = new ImageOptimizerService();
  });

  // ── verifyMagicBytes ──────────────────────────────────────────────────────────

  it('returns image/png for a valid PNG buffer', async () => {
    const mime = await service.verifyMagicBytes(PNG_BUFFER);
    expect(mime).toBe('image/png');
  });

  it('throws BadRequestException for PDF buffer', async () => {
    await expect(service.verifyMagicBytes(PDF_BUFFER)).rejects.toThrow(BadRequestException);
  });

  it('detects SVG via text heuristic', async () => {
    const mime = await service.verifyMagicBytes(SVG_HEADER);
    expect(mime).toBe('image/svg+xml');
  });

  it('accepts all ALLOWED_MIME_TYPES', () => {
    const expected = ['image/png', 'image/jpeg', 'image/gif', 'image/webp', 'image/svg+xml', 'image/tiff', 'image/bmp'];
    for (const mime of expected) {
      expect(ALLOWED_MIME_TYPES.has(mime)).toBe(true);
    }
  });

  // ── optimizeToWebP ────────────────────────────────────────────────────────────

  it('converts PNG to WebP and returns a buffer', async () => {
    const result = await service.optimizeToWebP(PNG_BUFFER, 'image/png');
    // Result must be a non-empty Buffer
    expect(Buffer.isBuffer(result)).toBe(true);
    expect(result.length).toBeGreaterThan(0);
  });

  it('converts JPEG to WebP and returns a buffer', async () => {
    const result = await service.optimizeToWebP(JPEG_BUFFER, 'image/jpeg');
    expect(Buffer.isBuffer(result)).toBe(true);
    expect(result.length).toBeGreaterThan(0);
  });

  it('skips WebP conversion for GIF (animation preservation)', async () => {
    const result = await service.optimizeToWebP(GIF_HEADER, 'image/gif');
    expect(result).toBe(GIF_HEADER);
  });

  it('skips WebP conversion for SVG (vector quality)', async () => {
    const result = await service.optimizeToWebP(SVG_HEADER, 'image/svg+xml');
    expect(result).toBe(SVG_HEADER);
  });

  it('falls back to original buffer when sharp receives corrupt data', async () => {
    const corrupt = Buffer.from([0x89, 0x50, 0x4e, 0x47]); // truncated PNG header
    const result = await service.optimizeToWebP(corrupt, 'image/png');
    // Service catches sharp error and returns original
    expect(result).toBe(corrupt);
  });

  // ── checkZipBomb ──────────────────────────────────────────────────────────────

  it('throws BadRequestException when actual size is > 3x declared AND > 5MB', async () => {
    const bigBuffer = Buffer.alloc(6 * 1024 * 1024, 0x00);
    const declaredSize = 1 * 1024 * 1024;
    await expect(service.checkZipBomb(bigBuffer, declaredSize)).rejects.toThrow(BadRequestException);
  });

  it('allows buffer when ratio > 3x but actual size <= 5MB', async () => {
    const buf = Buffer.alloc(4 * 1024 * 1024, 0x00);
    const declaredSize = 1024;
    await expect(service.checkZipBomb(buf, declaredSize)).resolves.toBeUndefined();
  });

  it('allows buffer when size matches declaration', async () => {
    const buf = Buffer.alloc(1024, 0x00);
    await expect(service.checkZipBomb(buf, 1024)).resolves.toBeUndefined();
  });

  // ── extractDimensions ─────────────────────────────────────────────────────────

  it('returns width and height from a real image buffer', async () => {
    const dims = await service.extractDimensions(PNG_BUFFER);
    expect(dims).toEqual({ width: 1, height: 1 });
  });

  it('returns {0,0} when sharp receives corrupt buffer', async () => {
    const corrupt = Buffer.from([0x89, 0x50, 0x4e, 0x47]); // truncated PNG
    const dims = await service.extractDimensions(corrupt);
    expect(dims).toEqual({ width: 0, height: 0 });
  });
});
