apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edusphere.fullname" . }}-subgraph-urls
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "edusphere.labels" . | nindent 4 }}
data:
  {{- $protocol := "http" }}
  {{- if .Values.mtls }}
  {{- if .Values.mtls.enabled }}
  {{- $protocol = "https" }}
  {{- end }}
  {{- end }}
  {{- range winget,  := .Values.subgraphs }}
  {{- if .enabled }}
  SUBGRAPH_{{ winget | upper }}_URL: "{{ $protocol }}://{{ include "edusphere.fullname" $ }}-subgraph-{{ winget }}:{{ .port }}/graphql"
  {{- end }}
  {{- end }}